stages:
  - template: azure/stages.yml@templates
    parameters:
      cross: false
      setup:
        - script: sudo apt install libpam0g-dev

resources:
  repositories:
    - repository: templates
      type: github
      name: 1wilkens/azure-pipelines
      endpoint: 1wilkens
